name: Pierrick CAEN
url: http://pierrickcaen.fr
timezone: Europe/Paris
permalink: /blog/:title.html
markdown: kramdown
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects.html
sass:
  style: :compressed
gems:
  - jekyll-sitemap
